List<String> allRecitation = [
  "Abdul Basit Abdul Samad(AbdulSamad_64kbps_QuranExplorer.Com)",
  "Abdul Basit Mujawwad(Abdul_Basit_Mujawwad_128kbps)",
  "Abdul Basit Murattal (Abdul_Basit_Murattal_64kbps)",
  "Abdullah Basfar(Abdullah_Basfar_64kbps)",
  "Abdullah Matroud(Abdullah_Matroud_128kbps)",
  "Abdurrahmaan As-Sudais (Abdurrahmaan_As-Sudais_64kbps)",
  "Abu Bakr_Ash-Shaatree(Abu_Bakr_Ash-Shaatree_64kbps)",
  "Ahmed Neana(Ahmed_Neana_128kbps)",
  "Ahmed Ibn Ali Al-Ajamy (Ahmed_ibn_Ali_al-Ajamy_64kbps_QuranExplorer.Com)",
  "Akram AlAlaqimy(Akram_AlAlaqimy_128kbps)",
  "Alafasy(Alafasy_64kbps)",
  "Ali Hajjaj AlSuesy(Ali_Hajjaj_AlSuesy_128kbps)",
  "Ali Jaber(Ali_Jaber_64kbps)",
  "Ayman Sowaid(Ayman_Sowaid_64kbps)",
  "Sahih Ibrahim(English/Sahih_Intnl_Ibrahim_Walk_192kbps)",
  "Fares Abbad(Fares_Abbad_64kbps)",
  "Ghamadi (Ghamadi_40kbps)",
  "Hani Rifai (Hani_Rifai_64kbps)",
  "Hudhaify (Hudhaify_64kbps)",
  "Al Husary (Husary_64kbps)",
  "Al Husary - Muallim (Husary_Muallim_128kbps)",
  "Al Husary - Mujawwad (Husary_Mujawwad_64kbps)",
  "Ibrahim Akhdar (Ibrahim_Akhdar_32kbps)",
  "Ibrahim Akhdar (Ibrahim_Akhdar_64kbps)",
  "Karim Mansoori (Karim_Mansoori_40kbps)",
  "Khaalid Abdullaah",
  "Al-Qahtaanee (Khaalid_Abdullaah_al-Qahtaanee_192kbps)",
  "Maher AlMuaiqly (MaherAlMuaiqly128kbps)",
  "Maher AlMuaiqly (Maher_AlMuaiqly_64kbps)",
  "Al Menshawi (Menshawi_16kbps)",
  "Al Menshawi (Menshawi_32kbps)",
  "Al Minshawy -Mujawwad (Minshawy_Mujawwad_64kbps)",
  "Al Minshawy -Murattal (Minshawy_Murattal_128kbps)",
  "Mohammad Al Tablaway (Mohammad_al_Tablaway_64kbps)",
  "Muhammad AbdulKareem (Muhammad_AbdulKareem_128kbps)",
  "Muhammad Ayyoub (Muhammad_Ayyoub_64kbps)",
  "Muhammad Jibreel (Muhammad_Jibreel_64kbps)",
  "Muhsin Al Qasim (Muhsin_Al_Qasim_192kbps)",
  "Basfar -MultiLanguage (MultiLanguage/Basfar_Walk_192kbps)",
  "Mustafa Ismail (Mustafa_Ismail_48kbps)",
  "Nabil Rifa3i (Nabil_Rifa3i_48kbps)",
  "Nasser Alqatami (Nasser_Alqatami_128kbps)",
  "Parhizgar (Parhizgar_48kbps)",
  "Sahl Yassin (Sahl_Yassin_128kbps)",
  "Salaah AbdulRahman Bukhatir (Salaah_AbdulRahman_Bukhatir_128kbps)",
  "Salah Al Budair (Salah_Al_Budair_128kbps)",
  "Saood Ash-Shuraym (Shuraym_64kbps)",
  "Yaser Salamah (Yaser_Salamah_128kbps)",
  "Yasser Ad-Dussary (Dussary_128kbps)",
  "Ahmed Ibn Ali Al-Ajamy (ahmed_ibn_ali_al_ajamy_128kbps)",
  "Aziz Alili (aziz_alili_128kbps)",
  "Khalefa Al Tunaiji (khalefa_al_tunaiji_64kbps)",
  "Mahmoud Ali Al Banna (mahmoud_ali_al_banna_32kbps)",
  "Hedayatfar - with translations by Fooladvand (translations/Fooladvand_Hedayatfar_40Kbps)",
  "Makarem Kabiri - with translations (translations/Makarem_Kabiri_16Kbps)",
  "Balayev - with azerbaijani translations (translations/azerbaijani/balayev)",
  "Besim Korkut - with translations (translations/besim_korkut_ajet_po_ajet)",
  "Farhat Hashmi - with Urdu translations (translations/urdu_farhat_hashmi)",
  "Shamshad Ali Khan -with Urdu translations (translations/urdu_shamshad_ali_khan_46kbps)",
  "Abdul Basit - warsh (warsh/warsh_Abdul_Basit_128kbps)",
  "Ibrahim Al Dosary -Yassin Al Jazaery -warsh (warsh/warsh_yassin_al_jazaery_64kbps)"
];
